package com.yida.boottracer.domain;
// Generated 2019-2-17 11:01:45 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.NamedEntityGraphs;
import javax.persistence.NamedSubgraph;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.apache.commons.lang3.StringUtils;

import com.yida.boottracer.enums.ApproveType;

/**
 * BizCodeApply generated by hbm2java
 */
@Entity
@Table(name = "biz_code_apply")

@NamedEntityGraphs(
		value = {
				@NamedEntityGraph(
						name = "BizCodeApply|sysMember|entDictProduct", attributeNodes = 
						{
								@NamedAttributeNode(value="sysMember",subgraph = "sysMember"),@NamedAttributeNode("entDictProduct")
						}
				)
		}
)

public class BizCodeApply extends AuditModel implements java.io.Serializable
{

	private Integer id;
	private Long version;
	private EntDictProduct entDictProduct;
	private SysMember sysMember;
	private String batchCode;
	private String fromCode;
	private String endCode;
	private Integer applyQty;
	private Integer deliveredQty;
	private Integer activatedQty;
	private String fileName;
	private Boolean downloaded;
	private String comment;
	private Integer approved;
	private String approveUser;
	private Date appproveTime;


	public BizCodeApply()
	{
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Version
	@Column(name = "Version")
	public Long getVersion()
	{
		return this.version;
	}

	public void setVersion(Long version)
	{
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID", nullable = false)
	public EntDictProduct getEntDictProduct()
	{
		return this.entDictProduct;
	}

	public void setEntDictProduct(EntDictProduct entDictProduct)
	{
		this.entDictProduct = entDictProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SysMemberID", nullable = false)
	public SysMember getSysMember()
	{
		return this.sysMember;
	}

	public void setSysMember(SysMember sysMember)
	{
		this.sysMember = sysMember;
	}

	@Column(name = "BatchCode", nullable = false, length = 256)
	public String getBatchCode()
	{
		return this.batchCode;
	}

	public void setBatchCode(String batchCode)
	{
		this.batchCode = batchCode;
	}

	@Column(name = "FromCode", nullable = true, length = 256)
	public String getFromCode()
	{
		return this.fromCode;
	}

	public void setFromCode(String fromCode)
	{
		this.fromCode = fromCode;
	}

	@Column(name = "EndCode", nullable = true, length = 256)
	public String getEndCode()
	{
		return this.endCode;
	}

	public void setEndCode(String endCode)
	{
		this.endCode = endCode;
	}

	@Column(name = "ApplyQty", nullable = false)
	public Integer getApplyQty()
	{
		return this.applyQty;
	}

	public void setApplyQty(Integer applyQty)
	{
		this.applyQty = applyQty;
	}

	@Column(name = "DeliveredQty", nullable = false)
	public Integer getDeliveredQty()
	{
		return this.deliveredQty;
	}

	public void setDeliveredQty(Integer deliveredQty)
	{
		this.deliveredQty = deliveredQty;
	}

	@Column(name = "ActivatedQty", nullable = false)
	public Integer getActivatedQty()
	{
		return this.activatedQty;
	}

	public void setActivatedQty(Integer activatedQty)
	{
		this.activatedQty = activatedQty;
	}

	@Column(name = "FileName", nullable = true, length = 256)
	public String getFileName()
	{
		return this.fileName;
	}

	public void setFileName(String fileName)
	{
		this.fileName = fileName;
	}

	@Column(name = "Downloaded", nullable = false)
	public Boolean isDownloaded()
	{
		return this.downloaded;
	}

	public void setDownloaded(Boolean downloaded)
	{
		this.downloaded = downloaded;
	}

	@Column(name = "Comment", length = 500)
	public String getComment()
	{
		return this.comment;
	}

	public void setComment(String comment)
	{
		this.comment = comment;
	}

	@Column(name = "Approved")
	public Integer getApproved()
	{
		return this.approved;
	}

	public void setApproved(Integer approved)
	{
		this.approved = approved;
	}

	@Column(name = "ApproveUser", length = 64)
	public String getApproveUser()
	{
		return this.approveUser;
	}

	public void setApproveUser(String approveUser)
	{
		this.approveUser = approveUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AppproveTime", length = 26)
	public Date getAppproveTime()
	{
		return this.appproveTime;
	}

	public void setAppproveTime(Date appproveTime)
	{
		this.appproveTime = appproveTime;
	}

}
