package com.yida.boottracer.domain;
// Generated 2019-1-24 21:32:37 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * BizPayment generated by hbm2java
 */
@Entity
@Table(name = "biz_payment")
public class BizPayment extends AuditModel implements java.io.Serializable
{

	private int id;
	private Long version;
	private SysMember sysMember;
	private String payCode;
	private int payType;
	private int payQty;
	private BigDecimal payMoney;
	private String payMethodName;
	private String remitter;
	private String tel;
	private Date payDate;
	private String comment;
	private String pic1;
	private String pic2;
	private String pic3;
	private String pic4;
	private String pic5;
	private boolean approved;
	private String approveUser;
	private Date appproveTime;
	
	public BizPayment()
	{
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Version
	@Column(name = "Version", nullable = false)
	public Long getVersion()
	{
		return this.version;
	}

	public void setVersion(Long version)
	{
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SysMemberID", nullable = false)
	public SysMember getSysMember()
	{
		return this.sysMember;
	}

	public void setSysMember(SysMember sysMember)
	{
		this.sysMember = sysMember;
	}

	@Column(name = "PayCode", nullable = false, length = 50)
	public String getPayCode()
	{
		return this.payCode;
	}

	public void setPayCode(String payCode)
	{
		this.payCode = payCode;
	}

	@Column(name = "PayType", nullable = false)
	public int getPayType()
	{
		return this.payType;
	}

	public void setPayType(int payType)
	{
		this.payType = payType;
	}

	@Column(name = "PayQty", nullable = false)
	public int getPayQty()
	{
		return this.payQty;
	}

	public void setPayQty(int payQty)
	{
		this.payQty = payQty;
	}

	@Column(name = "PayMoney", nullable = false, precision = 10)
	public BigDecimal getPayMoney()
	{
		return this.payMoney;
	}

	public void setPayMoney(BigDecimal payMoney)
	{
		this.payMoney = payMoney;
	}

	@Column(name = "PayMethodName", nullable = false, length = 256)
	public String getPayMethodName()
	{
		return this.payMethodName;
	}

	public void setPayMethodName(String payMethodName)
	{
		this.payMethodName = payMethodName;
	}

	@Column(name = "Remitter", nullable = false, length = 50)
	public String getRemitter()
	{
		return this.remitter;
	}

	public void setRemitter(String remitter)
	{
		this.remitter = remitter;
	}

	@Column(name = "Tel", nullable = false, length = 256)
	public String getTel()
	{
		return this.tel;
	}

	public void setTel(String tel)
	{
		this.tel = tel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PayDate", nullable = false, length = 10)
	public Date getPayDate()
	{
		return this.payDate;
	}

	public void setPayDate(Date payDate)
	{
		this.payDate = payDate;
	}

	@Column(name = "Comment", nullable = false, length = 500)
	public String getComment()
	{
		return this.comment;
	}

	public void setComment(String comment)
	{
		this.comment = comment;
	}

	@Column(name = "Pic1", nullable = false, length = 2048)
	public String getPic1()
	{
		return this.pic1;
	}

	public void setPic1(String pic1)
	{
		this.pic1 = pic1;
	}

	@Column(name = "Pic2", nullable = false, length = 2048)
	public String getPic2()
	{
		return this.pic2;
	}

	public void setPic2(String pic2)
	{
		this.pic2 = pic2;
	}

	@Column(name = "Pic3", nullable = false, length = 2048)
	public String getPic3()
	{
		return this.pic3;
	}

	public void setPic3(String pic3)
	{
		this.pic3 = pic3;
	}

	@Column(name = "Pic4", nullable = false, length = 2048)
	public String getPic4()
	{
		return this.pic4;
	}

	public void setPic4(String pic4)
	{
		this.pic4 = pic4;
	}

	@Column(name = "Pic5", nullable = false, length = 2048)
	public String getPic5()
	{
		return this.pic5;
	}

	public void setPic5(String pic5)
	{
		this.pic5 = pic5;
	}

	@Column(name = "Approved", nullable = false)
	public boolean isApproved()
	{
		return this.approved;
	}

	public void setApproved(boolean approved)
	{
		this.approved = approved;
	}

	@Column(name = "ApproveUser", nullable = false, length = 64)
	public String getApproveUser()
	{
		return this.approveUser;
	}

	public void setApproveUser(String approveUser)
	{
		this.approveUser = approveUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AppproveTime", nullable = false, length = 26)
	public Date getAppproveTime()
	{
		return this.appproveTime;
	}

	public void setAppproveTime(Date appproveTime)
	{
		this.appproveTime = appproveTime;
	}

}
