package com.yida.boottracer.domain;
// Generated 2018-12-17 21:12:26 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.validation.constraints.NotBlank;

/**
 * DictMemberType generated by hbm2java
 */
@Entity
@Table(name = "dict_member_type")
public class DictMemberType implements java.io.Serializable
{

	private Integer id;
	private Integer freeCodeQty;
	private Integer holdTime;
	private Boolean isDefault;
	private Boolean isDeleted;
	private String comment;
	private String name;
	private Long version=0L;
	
	private Set<DictMemberPrice> dictMemberPrices = new HashSet<>();

	public DictMemberType()
	{
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 256)
	@NotBlank(message = "名称不能为空")
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}
	
	@Column(name = "FreeCodeQty", nullable = false)
	public Integer getFreeCodeQty()
	{
		return this.freeCodeQty;
	}

	public void setFreeCodeQty(Integer freeCodeQty)
	{
		this.freeCodeQty = freeCodeQty;
	}

	@Column(name = "HoldTime", nullable = false)
	public Integer getHoldTime()
	{
		return this.holdTime;
	}

	public void setHoldTime(Integer holdTime)
	{
		this.holdTime = holdTime;
	}

	@Column(name = "IsDefault", nullable = false)
	public Boolean isIsDefault()
	{
		return this.isDefault;
	}

	public void setIsDefault(Boolean isDefault)
	{
		this.isDefault = isDefault;
	}

	@Column(name = "IsDeleted", nullable = false)
	public Boolean isIsDeleted()
	{
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted)
	{
		this.isDeleted = isDeleted;
	}

	@Column(name = "Comment", length = 256)
	public String getComment()
	{
		return this.comment;
	}

	public void setComment(String comment)
	{
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dictMemberType",cascade= {CascadeType.ALL})
	public Set<DictMemberPrice> getDictMemberPrices()
	{
		return this.dictMemberPrices;
	}

	public void setDictMemberPrices(Set<DictMemberPrice> dictMemberPrices)
	{
		this.dictMemberPrices = dictMemberPrices;
	}

	@Version
	@Column(name = "version", nullable = false)
	public Long getVersion()
	{
		return this.version;
	}

	public void setVersion(Long version)
	{
		this.version = version;
	}
}
