package com.yida.boottracer.domain;
// Generated 2018-12-2 22:28:19 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import javax.validation.constraints.*;

/**
 * DictCommon generated by hbm2java
 */
@Entity
@Table(name = "dict_common", uniqueConstraints = @UniqueConstraint(columnNames = { "DictType", "Code" }))
public class DictCommon implements java.io.Serializable
{

	private int id;
	private int dictType;
	private String code;	
	private boolean isDeleted;
	private String comment;
	private String name;
	private Long version=0L;

	public DictCommon()
	{
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "DictType", nullable = false)
	public int getDictType()
	{
		return this.dictType;
	}

	public void setDictType(int dictType)
	{
		this.dictType = dictType;
	}

	@Column(name = "Code", nullable = false, length = 45)
	@NotBlank(message = "编码不能为空")
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "Name", nullable = false, length = 256)
	@NotBlank(message = "名称不能为空")
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted()
	{
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted)
	{
		this.isDeleted = isDeleted;
	}

	@Column(name = "Comment", length = 256)
	public String getComment()
	{
		return this.comment;
	}

	public void setComment(String comment)
	{
		this.comment = comment;
	}

	@Version
	@Column(name = "version", nullable = false)
	public Long getVersion()
	{
		return this.version;
	}

	public void setVersion(Long version)
	{
		this.version = version;
	}
}
