package com.yida.boottracer.domain;
// Generated 2018-12-2 22:28:19 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DictCommon generated by hbm2java
 */
@Entity
@Table(name = "dict_common")
public class DictCommon implements java.io.Serializable
{

	private int id;
	private int dictType;
	private String code;
	private String name;
	private boolean isDeleted;
	private String comment;


	public DictCommon()
	{
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "DictType", nullable = false)
	public int getDictType()
	{
		return this.dictType;
	}

	public void setDictType(int dictType)
	{
		this.dictType = dictType;
	}

	@Column(name = "Code", nullable = false, length = 45)
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "Name", nullable = false, length = 256)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted()
	{
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted)
	{
		this.isDeleted = isDeleted;
	}

	@Column(name = "Comment", length = 256)
	public String getComment()
	{
		return this.comment;
	}

	public void setComment(String comment)
	{
		this.comment = comment;
	}

}
