package com.yida.boottracer.domain;
// Generated 2019-1-8 21:56:57 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.NamedEntityGraphs;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * EntDictCoder generated by hbm2java
 */
@NamedEntityGraphs(value = {
	    @NamedEntityGraph(name = "EntDictCoder.details", attributeNodes = {
	        @NamedAttributeNode("details")
	    })
	})
@Entity
@Table(name = "ent_dict_coder")
public class EntDictCoder extends AuditModel implements java.io.Serializable
{

	private int id;
	private Long version;
	private SysMember sysMember;
	private String code;
	private String name;
	private boolean approved;
	private String comment;
	private boolean isDeleted;
	private Set<EntDictCoderDetail> details = new HashSet<>();	
	
	private String description;

	public EntDictCoder()
	{
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Version
	@Column(name = "Version", nullable = false)
	public Long getVersion()
	{
		return this.version;
	}

	public void setVersion(Long version)
	{
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SysMemberID", nullable = false)
	public SysMember getSysMember()
	{
		return this.sysMember;
	}

	public void setSysMember(SysMember sysMember)
	{
		this.sysMember = sysMember;
	}

	@Column(name = "Code", nullable = false, length = 45)
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "Name", nullable = false, length = 256)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "Approved", nullable = false)
	public boolean isApproved()
	{
		return this.approved;
	}

	public void setApproved(boolean approved)
	{
		this.approved = approved;
	}
	
	@Column(name = "Description", length = 256)
	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}	
	
	@Column(name = "Comment", length = 45)
	public String getComment()
	{
		return this.comment;
	}

	public void setComment(String comment)
	{
		this.comment = comment;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted()
	{
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted)
	{
		this.isDeleted = isDeleted;
	}

	@JsonManagedReference(value="EntDictCoder-EntDictCoderDetail")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entDictCoder",cascade= {CascadeType.PERSIST,CascadeType.REFRESH,CascadeType.REMOVE,CascadeType.DETACH,CascadeType.MERGE}, orphanRemoval=true /*jpa 2 新增，允许删除子对象*/)
	public Set<EntDictCoderDetail> getDetails()
	{
		return this.details;
	}

	public void setDetails(Set<EntDictCoderDetail> details)
	{
		this.details = details;
	}
}
