package com.yida.boottracer.domain;
// Generated 2019-1-3 5:00:43 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.validation.constraints.NotBlank;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * EntDictCategory generated by hbm2java
 */
@Entity
@Table(name = "ent_dict_category")
public class EntDictCategory extends AuditModel implements java.io.Serializable
{

	private int id;
	private EntDictCategory parent;
	private SysMember sysMember;
	private String code;
	private String name;
	private String comment;
	private Set<EntDictCategory> children = new HashSet<>();
	private Long version;
	private boolean isDeleted;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ParentID")
	@JsonBackReference(value="self")
	public EntDictCategory getParent()
	{
		return this.parent;
	}

	public void setParent(EntDictCategory parent)
	{
		this.parent = parent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SysMemberID", nullable = false)
	@JsonBackReference(value="EntDictCategory-SysMember")
	public SysMember getSysMember()
	{
		return this.sysMember;
	}

	public void setSysMember(SysMember sysMember)
	{
		this.sysMember = sysMember;
	}

	@Column(name = "Code", nullable = false, length = 45)
	@NotBlank(message = "编码不能为空")
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}
	
	@NotBlank(message = "名称不能为空")
	@Column(name = "Name", nullable = false, length = 45)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}
	

	@Column(name = "Comment", length = 256)
	public String getComment()
	{
		return this.comment;
	}

	public void setComment(String comment)
	{
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parent")
	@JsonManagedReference(value="self")
	public Set<EntDictCategory> getChildren()
	{
		return this.children;
	}

	public void setChildren(Set<EntDictCategory> children)
	{
		this.children = children;
	}
	
	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted()
	{
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted)
	{
		this.isDeleted = isDeleted;
	}

	@Version
	@Column(name = "Version", nullable = false)
	public Long getVersion()
	{
		return this.version;
	}

	public void setVersion(Long version)
	{
		this.version = version;
	}

}
