package com.yida.boottracer.domain;
// Generated 2019-1-12 15:21:28 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.NamedEntityGraphs;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * EntDictProduct generated by hbm2java
 */
@Entity
@Table(name = "ent_dict_product")
@NamedEntityGraphs(value = {
	    @NamedEntityGraph(name = "EntDictProduct.entDictCategory-entDictCoder", attributeNodes = {
	        @NamedAttributeNode("entDictCategory"),@NamedAttributeNode("entDictCoder")
	    })
	})
public class EntDictProduct extends AuditModel implements java.io.Serializable
{

	private int id;
	private Long version;
	private EntDictCategory entDictCategory;
	private EntDictCoder entDictCoder;
	private String code;
	private String name;
	private String spec;
	private String period;
	private Integer gift;
	private String pic;
	private String descVideo;
	private String operVideo;
	private String onlineVideo;
	private String richDescription;
	private String comment;
	private String userCustom1;
	private String userCustom2;
	private String userCustom3;
	private String userCustom4;
	private String userCustom5;
	private String userCustom6;
	private String userCustom7;
	private String userCustom8;
	private String userCustom9;
	private String userCustom10;
	private boolean isDeleted;	
	private SysMember sysMember;

	public EntDictProduct()
	{
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Version
	@Column(name = "Version", nullable = false)
	public Long getVersion()
	{
		return this.version;
	}

	public void setVersion(Long version)
	{
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CategoryID", nullable = false)
	public EntDictCategory getEntDictCategory()
	{
		return this.entDictCategory;
	}

	public void setEntDictCategory(EntDictCategory entDictCategory)
	{
		this.entDictCategory = entDictCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CoderID", nullable = false)
	public EntDictCoder getEntDictCoder()
	{
		return this.entDictCoder;
	}

	public void setEntDictCoder(EntDictCoder entDictCoder)
	{
		this.entDictCoder = entDictCoder;
	}

	@Column(name = "Code", nullable = false, length = 45)
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "Name", nullable = false, length = 256)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "Spec", length = 256)
	public String getSpec()
	{
		return this.spec;
	}

	public void setSpec(String spec)
	{
		this.spec = spec;
	}

	@Column(name = "Period", length = 256)
	public String getPeriod()
	{
		return this.period;
	}

	public void setPeriod(String period)
	{
		this.period = period;
	}

	@Column(name = "Gift")
	public Integer getGift()
	{
		return this.gift;
	}

	public void setGift(Integer gift)
	{
		this.gift = gift;
	}

	@Column(name = "Pic", length = 2048)
	public String getPic()
	{
		return this.pic;
	}

	public void setPic(String pic)
	{
		this.pic = pic;
	}

	@Column(name = "DescVideo", length = 2048)
	public String getDescVideo()
	{
		return this.descVideo;
	}

	public void setDescVideo(String descVideo)
	{
		this.descVideo = descVideo;
	}

	@Column(name = "OperVideo", length = 2048)
	public String getOperVideo()
	{
		return this.operVideo;
	}

	public void setOperVideo(String operVideo)
	{
		this.operVideo = operVideo;
	}

	@Column(name = "OnlineVideo", length = 2048)
	public String getOnlineVideo()
	{
		return this.onlineVideo;
	}

	public void setOnlineVideo(String onlineVideo)
	{
		this.onlineVideo = onlineVideo;
	}

	@Column(name = "RichDescription", length = 16777215)
	public String getRichDescription()
	{
		return this.richDescription;
	}

	public void setRichDescription(String richDescription)
	{
		this.richDescription = richDescription;
	}

	@Column(name = "Comment", length = 256)
	public String getComment()
	{
		return this.comment;
	}

	public void setComment(String comment)
	{
		this.comment = comment;
	}

	@Column(name = "UserCustom1", length = 256)
	public String getUserCustom1()
	{
		return this.userCustom1;
	}

	public void setUserCustom1(String userCustom1)
	{
		this.userCustom1 = userCustom1;
	}

	@Column(name = "UserCustom2", length = 256)
	public String getUserCustom2()
	{
		return this.userCustom2;
	}

	public void setUserCustom2(String userCustom2)
	{
		this.userCustom2 = userCustom2;
	}

	@Column(name = "UserCustom3", length = 256)
	public String getUserCustom3()
	{
		return this.userCustom3;
	}

	public void setUserCustom3(String userCustom3)
	{
		this.userCustom3 = userCustom3;
	}

	@Column(name = "UserCustom4", length = 256)
	public String getUserCustom4()
	{
		return this.userCustom4;
	}

	public void setUserCustom4(String userCustom4)
	{
		this.userCustom4 = userCustom4;
	}

	@Column(name = "UserCustom5", length = 256)
	public String getUserCustom5()
	{
		return this.userCustom5;
	}

	public void setUserCustom5(String userCustom5)
	{
		this.userCustom5 = userCustom5;
	}

	@Column(name = "UserCustom6", length = 256)
	public String getUserCustom6()
	{
		return this.userCustom6;
	}

	public void setUserCustom6(String userCustom6)
	{
		this.userCustom6 = userCustom6;
	}

	@Column(name = "UserCustom7", length = 256)
	public String getUserCustom7()
	{
		return this.userCustom7;
	}

	public void setUserCustom7(String userCustom7)
	{
		this.userCustom7 = userCustom7;
	}

	@Column(name = "UserCustom8", length = 256)
	public String getUserCustom8()
	{
		return this.userCustom8;
	}

	public void setUserCustom8(String userCustom8)
	{
		this.userCustom8 = userCustom8;
	}

	@Column(name = "UserCustom9", length = 256)
	public String getUserCustom9()
	{
		return this.userCustom9;
	}

	public void setUserCustom9(String userCustom9)
	{
		this.userCustom9 = userCustom9;
	}

	@Column(name = "UserCustom10", length = 256)
	public String getUserCustom10()
	{
		return this.userCustom10;
	}

	public void setUserCustom10(String userCustom10)
	{
		this.userCustom10 = userCustom10;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SysMemberID")	                          	
	public SysMember getSysMember()
	{
		return this.sysMember;
	}

	public void setSysMember(SysMember sysMember)
	{
		this.sysMember = sysMember;
	}
	
	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted()
	{
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted)
	{
		this.isDeleted = isDeleted;
	}
}
