package com.yida.boottracer.domain.test;
// Generated 2018-11-20 12:06:58 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.NamedSubgraph;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * TestOrder generated by hbm2java
 */
@Entity
@Table(name = "test_order")
@NamedEntityGraph(name = "graph.Order.items", attributeNodes = {
		@NamedAttributeNode(value = "items", subgraph = "items") }, subgraphs = {
				@NamedSubgraph(name = "items", attributeNodes = { @NamedAttributeNode("product") }) })
public class Order implements java.io.Serializable
{

	private long id;
	private Integer version;
	private String orderNumber;
	private Set<OrderItem> items = new HashSet<OrderItem>();

	public Order()
	{
	}

	public Order(long id)
	{
		this.id = id;
	}

	public Order(long id, String orderNumber, Set<OrderItem> items)
	{
		this.id = id;
		this.orderNumber = orderNumber;
		this.items = items;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", updatable = false, nullable = false)
	public long getId()
	{
		return this.id;
	}

	public void setId(long id)
	{
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion()
	{
		return this.version;
	}

	public void setVersion(Integer version)
	{
		this.version = version;
	}

	@Column(name = "order_number")
	public String getOrderNumber()
	{
		return this.orderNumber;
	}

	public void setOrderNumber(String orderNumber)
	{
		this.orderNumber = orderNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order", cascade = { CascadeType.ALL })
	public Set<OrderItem> getItems()
	{
		return this.items;
	}

	public void setItems(Set<OrderItem> items)
	{
		this.items = items;
	}

}
