package com.yida.boottracer.domain.test;
// Generated 2018-11-20 12:06:58 by Hibernate Tools 5.2.10.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TestOrderItem generated by hbm2java
 */
@Entity
@Table(name = "test_order_item")

public class OrderItem implements java.io.Serializable
{

	private long id;
	private Integer version;
	private Order order;
	private Product product;
	private Integer quantity;

	public OrderItem()
	{
	}

	public OrderItem(long id)
	{
		this.id = id;
	}

	public OrderItem(long id, Order order, Product product, Integer quantity)
	{
		this.id = id;
		this.order = order;
		this.product = product;
		this.quantity = quantity;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", updatable = false, nullable = false)
	public long getId()
	{
		return this.id;
	}

	public void setId(long id)
	{
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion()
	{
		return this.version;
	}

	public void setVersion(Integer version)
	{
		this.version = version;
	}

	// 设置级联更新，否则必需先持久化主表，再持久化从表
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	@JsonIgnore
	public Order getOrder()
	{
		return this.order;
	}

	public void setOrder(Order order)
	{
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Product getProduct()
	{
		return this.product;
	}

	public void setProduct(Product product)
	{
		this.product = product;
	}

	@Column(name = "quantity")
	public Integer getQuantity()
	{
		return this.quantity;
	}

	public void setQuantity(Integer quantity)
	{
		this.quantity = quantity;
	}

}
